### ISSUE TITLE
某个“罢”的异体字字形拆解有误

### ISSUE THREAD

**Issue by whiterkim** [yi-bai/zi-tools#14]
见：
https://zi.tools/zi/⿱罒⿰䏍⿱尚𰀠?secondary=ids

其中“⿱罒⿰䏍⿱尚𰀠”的“尚”应为“上”，搜索“⿱罒⿰䏍⿱上𰀠”则无法找到正确的字型。

**Comment by yi-bai** [comment]
已更正，谢谢
